# Generated by Django 6.0.7 on 2026-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_task_due_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='True if on the Pro tier'),
        ),
    ]
