# Generated by Django 6.0.7 on 2026-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_workspace_project_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_pro',
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
